### ISSUE TITLE
Cannot install with use-package

### ISSUE THREAD

**Issue by sondr3** [alex-hhh/emacs-sql-indent#59] opened 2018-02-11 15:51 UTC
There's a different package on MELPA that has the same name that overrides this package and I haven't been able to install this package with `use-package` because of it. I've tried with the `:pin gnu` keyword but it doesn't seem to do anything. Currently doing this locally but it's not ideal. 😄

**Comment by alex-hhh** [comment] 2018-02-11 22:15
I don't use `use-package` myself, so I cannot help you with this question.  I will leave this issue open and added the `help wanted` label in case someone knows the answer.

**Comment by PierreTechoueyres** [comment] 2018-02-12 21:24
I've tried this simple test:
After cloning https://github.com/jwiegley/use-package locally I've launched in the repo root directory
```emacs  -q -L . -l test-sqlind.el```

Where `test-sqlind.el` contains is bellow.
```elisp
(setq package-archives
      (quote
       (("local"     . "~/Travail/VCS/emacs-local-repos/")
	("gnu"       . "https://elpa.gnu.org/packages/")
	("marmalade" . "https://marmalade-repo.org/packages/")
	("orgmode"   . "http://orgmode.org/elpa/")
	("melpa"     . "https://melpa.org/packages/"))))

;; This is only needed once, near the top of the file
(eval-when-compile
  ;; Following line is not needed if use-package.el is in ~/.emacs.d
  (add-to-list 'load-path "~/Travail/VCS/emacs-use-package")
  (require 'use-package))

(use-package sql-indent
  :ensure t
  :pin gnu)
```
And it seem's to work as expected: the package is installed from the gnu repository.

**Comment by sondr3** [comment] 2018-02-12 21:38
Thanks, I’ll try again tomorrow. I couldn’t get it to work locally. Might actually be because I had a folder named `sql-indent-2018something` In my `elpa/` folder when I think about it. I’ll let you know 😄

**Comment by alex-hhh** [comment] 2018-02-18 02:28
@PierreTechoueyres , thanks for looking into this.  I will close this issue as it looks like the problem is solved.

**Closed by alex-hhh** 2018-02-18 02:28 UTC
Labels: question
