### ISSUE TITLE
Incorrect detection / indentation of case conditions

### ISSUE THREAD

**Issue by PierreTechoueyres** [alex-hhh/emacs-sql-indent#29] opened 2017-06-09 20:03 UTC
I think there is inconsistency between the two cases statements bellow:
```sql
select y ,
       case
         when foo>5 then "great"
         when foo=5 then "normal"
         else "poor"
       end as level
from   bar;

declare
  dummy number;
begin
  case ind
  when 1 then dummy := 'Guy';
  when 2 then dummy := 'Abc';
  when 3 then dummy := 'Def'; 
  else dummy := 'World';
  end case;
end;
/

-- Local Variables:
-- mode: sqlind-minor
-- mode: sql
-- tab-width: 2
-- indent-tabs-mode: nil
-- sql-product: oracle
-- End:
```

I expected they will both indent the same way, but the second one was not detected as the first.

**Comment by alex-hhh** [comment] 2017-06-12 10:11
This works as intended, even though it is a bit confusing.  The first statement is a "case expression", the second one is a "case statement".     You can get them to indent the same by changing the syntax symbols for the two to match.

I pushed some fixes to correctly detect code inside the when blocks, this might help.

**Comment by PierreTechoueyres** [comment] 2017-06-12 22:45
I'm sorry but I fail to find how to do this.
I want to obtain the result bellow, but the syntax for the line ```when 1 then ...``` return ```(((block-start when) . 177) ((in-block case "") . 177))``` where the ```when foo>5 ...``` return ```((case-clause . 19) (select-column-continuation . 1) (statement-continuation . 1))```
I don't understand how to increase the indent for the second case without increasing the indent of the default block.

```sql
select y ,
       case
         when foo>5 then "great"
         when foo=5 then "normal"
         else "poor"
       end as level
from   bar;

declare
  dummy number;
begin
  case ind
    when 1 then dummy := 'Guy';
    when 2 then dummy := 'Abc';
    when 3 then dummy := 'Def'; 
    else dummy := 'World';
  end case;
end;
/

-- Local Variables:
-- mode: sqlind-minor
-- mode: sql
-- tab-width: 2
-- indent-tabs-mode: nil
-- sql-product: oracle
-- End:
```

**Comment by PierreTechoueyres** [comment] 2017-06-12 22:46
Thank you for working on this and sorry for my bad English.

**Comment by alex-hhh** [comment] 2017-06-13 11:00
I pushed a fix for the anchor point for `(in-block case ...)` syntax.  This was a bug preventing the indentation functions to work correctly.

----

To get the two cases indented as you want, you will need to add your own indentation function:

```emacs-lisp
(defun indent-case-statement-items (syntax base-indentation)
  ;; Look for a syntax of ((block-start when) (in-block case "") ...)
  ;; or ((block-start else) (in-block case "") ...)
  (let ((outer (sqlind-outer-context syntax)))
    (if (and (eq 'in-block (sqlind-syntax-symbol outer))
             (eq 'case (sqlind-syntax-keyword outer))
             (eq 'block-start (sqlind-syntax-symbol syntax))
             (memq (sqlind-syntax-keyword syntax) '(when else)))
        (+ base-indentation sqlind-basic-offset)
      base-indentation)))

(defvar my-indentation
  `((block-start indent-case-statement-items)
    (case-clause +)
    ,@sqlind-default-indentation-offsets-alist))
```

If you like pattern matching, you can also use the fancy `pcase` construct to match the syntax object:

```emacs-lisp
(defun indent-case-statement-items (syntax base-indentation)
  ;; Look for a syntax of ((block-start when) (in-block case "") ...)
  ;; or ((block-start else) (in-block case "") ...)
  (pcase syntax
    (`(((block-start ,(or when else)) . ,_)
       ((in-block case ,_) . ,_)
       . ,_)
      (+ base-indentation sqlind-basic-offset))
    (_
     base-indentation)))
```

## So why is this so complicated?  

The problem is that the "else" keyword needs to be indented differently depending on whether it is part of a `case` statement or and `if` statement.  Consider the example below: the indentation engine cannot really look only at `block-start` or `(block-start else)` to indent both lines correctly.

It would be nice if the specification of `sqlind-indentation-offsets-alist` could be extended so that more complex cases can be matched, but I don't really have time to think about an elegant solution.

```sql
declare
  dummy number;
begin
  case ind
    when 1 then dummy := 'Guy';
    when 2 then dummy := 'Abc';
    when 3 then dummy := 'Def'; 
    else dummy := 'World'; -- (((block-start else) . 33) ((in-block case "") . 33))
  end case;

  if a = b; then
    a := 'b';
  else                     -- (((block-start else) . 238) ((in-block if "") . 238))
    a := 'c';
  end if;
end;
/
```

**Comment by PierreTechoueyres** [comment] 2017-06-14 00:22
First thank you very much for the solution. I'll update the ```sql-indent-left.el``` and add / update tests this week. Of course I didn't think enough of my tests cases and I forgot another use of ```case``` statement. See below the assignment for super_dumy.
```sql
select y ,
       case
         when foo>5 then "great"
         when foo=5 then "normal"
         else "poor"
       end as level
from   bar;

declare
  dummy number;
  super_dummy varchar2(255);
begin
  case ind
    when 1 then dummy := 'Guy';
    when 2 then dummy := 'Abc';
    when 3 then dummy := 'Def'; 
    else dummy := 'World';
  end case;

  super_dummy := 'Hy !'
   || case ind
    when 1 then dummy := 'Guy';
    when 2 then dummy := 'Abc';
    when 3 then dummy := 'Def'; 
    else dummy := 'World';
  end case;
end;
/

-- Local Variables:
-- mode: sqlind-minor
-- mode: sql
-- tab-width: 2
-- indent-tabs-mode: nil
-- sql-product: oracle
-- End:
```

**Comment by alex-hhh** [comment] 2017-06-15 11:31
I don't think the last example you provided is valid PL/SQL code.  Regardless,
as a workaround, you can put brackets around the case statement, like so:

```sql
super_dummy := 'Hy !'
  || (case ind
      when 1 then 'Guy'
      when 2 then 'Abc'
      when 3 then 'Def'
      else 'World'
      end case)
  || ' def';
```

Since the case expression is part of a larger expression, the code would have
to parse the entire expression to provide correct syntactic information.  This
is too complex, so instead, all the lines of the entire expression are
classified as a `statement-continuation`.  You can use brackets, to group and
indent sub-expressions as needed, this should be supported for expressions of
any complexity.

-------------------------------------------------------------------------------

The examples below summarize what is supported and what is not.

```sql
-- SUPPORTED: case expression immediately after assignment
var := case ind
       when 1 then 'Guy'
       when 2 then 'Abc'
       when 3 then 'Def'
       else 'World'
       end case;

-- NOT SUPPORTED: any complex expression involving a case expression.  entire
-- expression is a 'statement-continuation
var := 'abc'
  || case ind
  when 1 then 'Guy'
  when 2 then 'Abc'
  when 3 then 'Def'
  else 'World'
  end case;

-- WORKAROUND: use brackets instead
var := 'abc'
  || (case ind
      when 1 then 'Guy'
      when 2 then 'Abc'
      when 3 then 'Def'
      else 'World'
      end case);

-- SUPPORTED: case expression as select column
select col1,
       case ind
       when 1 then 'Guy'
       when 2 then 'Abc'
       when 3 then 'Def'
       else 'World'
       end case,
       col2,
  from some_table;

-- NOT SUPPORTED: any complex expression involving a case expression in a
-- select column.  Entire column is a 'select-column-continuation
select col1,
       'abc' || case ind
         when 1 then 'Guy'
         when 2 then 'Abc'
         when 3 then 'Def'
         else 'World'
         end case,
       col2,
  from some_table;

-- WORKAROUND: use brackets instead
select col1,
       'abc' || (case ind
                 when 1 then 'Guy'
                 when 2 then 'Abc'
                 when 3 then 'Def'
                 else 'World'
                 end case),
       col2,
  from some_table;
```

**Closed by alex-hhh** 2017-06-15 11:31 UTC
