### ISSUE TITLE
SQL functions add a level of indentation to code below

### ISSUE THREAD

**Issue by bopjesvla** [alex-hhh/emacs-sql-indent#54] opened 2018-01-02 15:08 UTC
Current behavior:

```sql
create function a() returns int AS $$
  select 5
  $$;

  SELECT a();
```

Expected:

```sql
create function a() returns int AS $$
  select 5
$$;

SELECT a();
```

**Comment by alex-hhh** [comment] 2018-01-02 21:54
Thanks for reporting this.  Can you tell me what SQL dialect is this? Thanks, Alex.

**Comment by bopjesvla** [comment] 2018-01-03 13:42
Thanks for the quick reply! Dollar-quoting of strings may be Postgres-specific, other than that it's all in the SQL standard.

**Comment by alex-hhh** [comment] 2018-01-03 14:08
I added support for the $$ quote syntax in #55 with the following caveats:

* $$ quote syntax is only recognized when `sql-product` is set to 'postgres
* The syntax is recognized only for "create" statements
* The default indentation rules will not indent this as the example you provided -- this is not a bug, as indentation rules are a mater of personal preference.  To indent them as you shown in your example, you will need to use the following configuration (the file [sql-indent.org](/alex-hhh/emacs-sql-indent/blob/master/sql-indent.org) explains how to customize the indentation rules):

```emacs-lisp
(defvar my-sql-indentation-offsets-alist
  `((in-begin-block sqlind-use-anchor-indentation +)
    (block-end sqlind-use-anchor-indentation)
    ,@sqlind-default-indentation-offsets-alist))

(add-hook 'sqlind-minor-mode-hook
          (lambda ()
            (setq sqlind-indentation-offsets-alist
                  my-sql-indentation-offsets-alist)))
```

If you want to test the changes they are available in the `pr54` branch if you clone this repo.  Otherwise, I will merge the pull request in a day or so.

Best Regards,
Alex.

**Comment by alex-hhh** [comment] 2018-01-06 03:34
Merged the fix into the master branch, please let me know if you have any problems with it.

**Closed by alex-hhh** 2018-01-06 03:34 UTC
Labels: defect
