### ISSUE TITLE
Invalid indentation for recursive if/end if

### ISSUE THREAD

**Issue by PierreTechoueyres** [alex-hhh/emacs-sql-indent#4] opened 2017-03-21 18:49 UTC
I've trouble correctly indenting recursive if / then / end if;
The attached file isn't correctly indented. Any clue to start resolving this ?
The result bellow isn't what I expect.
``` sql
begin
  if 1 = 0 then
    if 1 = 0 then
    null;
  else
    null;
  end if;
  elsif 1 = 2
  if 1 = 0 then
    null;
  else
    null;
    end if;
  else
    null;
  end if;
end;
/
[test.multi-if.sql.txt](https://github.com/alex-hhh/emacs-sql-indent/files/859318/test.multi-if.sql.txt)


```

**Comment by alex-hhh** [comment] 2017-03-22 10:08
This is a know issue, and it is not simple to fix.  The workaround is to use `begin/end` blocks around the nested if statements, as in the example below.  I pushed a fix for indenting an `end if` line when there's an `elsif` in the if-else chain, see deb9885.

Unfortunately, I do not have time to fix this issue.  If you want to try fixing it, the problem is that `sqlind-beginning-of-statement-1` does not detect the beginning of the statement correctly for nested if blocks, so the `sqlind-syntax-of-line` function computes an incorrect syntax.

```sql
begin
  if 1 = 0 then
    begin
      if 1 = 0 then
        null;
      else
        null;
      end if;
    end;
  elsif 1 = 2
    begin
      if 1 = 0 then
        null;
      else
        null;
      end if;
    end;
  else
    null;
  end if;
end;
/
```

**Comment by PierreTechoueyres** [comment] 2017-03-23 00:27
Thanks for the hint. Unfortunately I must work with existing code and I can't enclose If blocks.
I'll try to work on this. Thanks for the start point.

**Closed** 2017-03-23 10:18 UTC
Labels: bug

**Comment by alex-hhh** [comment] 2017-03-23 10:20
After a bit of thinking I think I got this working.   Can you please try it out and see if it OK?

I wrote this code about 10 years ago and back than this seemed like a hard task...

**Comment by PierreTechoueyres** [comment] 2017-03-23 11:07
Whaou, You're faster than light !!!
Many thanks for fixing this. And you've maybe wrote this code 10 years ago but it's always useful (at least for me).
